### ISSUE TITLE
Can you explain what your bot does

### ISSUE THREAD

**Issue by Amazon-Hate-it-But-Need-it** [CapedBojji/amazon-vet-bot#1]
Can you give us a low level explanation of how your bot works/ what it does?

**Comment by CapedBojji** [comment]
lol I gotta private this repo sorry. Its not done but it uses imgui for the interface and retrieves the code from gmail. uses selenium in the [UI](https://gyazo.com/bc8c6300d26655d75524f5986b110abb). Its almost done. this repo is very out of date i havent pushed the changes i have been working on for like 2 weeks
